sudo: false
language: c++
os:
  - linux
dist: trusty
cache: ccache

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libsdl1.2-dev
    - libgc-dev

before_script:
  - git submodule update --init
  - mkdir -p ext && cd ext && wget https://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.tar.gz && tar xf cmake-3.8.0-Linux-x86_64.tar.gz
  - PATH=$TRAVIS_BUILD_DIR/ext/cmake-3.8.0-Linux-x86_64/bin:$PATH sh make-llvm.sh
script:
  - make test
